### ISSUE TITLE
Make the `Language` field a dropdown list instead of a text field

### ISSUE THREAD

**Issue by Korb** [benchen71/epub-metadata-editor#100]
Or, alternatively, a text field with automatic filtering of suitable values ​​from a drop-down list with a prohibition to save values ​​other than those allowed in this field:

![2024-12-09_15-44-17](https://github.com/user-attachments/assets/190bf977-5438-4ffe-9e92-bec280afca3f)

**Comment by benchen71** [comment]
I don't think this is possible since (as far as I know) the contents of this field is not narrowly defined by the opf specifications. For example, the EPUB I am using for my testing has language "en-US".
