### ISSUE TITLE
Error Saving Epub

### ISSUE THREAD

**Issue by ihopethisnameworks** [benchen71/epub-metadata-editor#19]
Recieve the following when saving when attempting to save.  I'm not competent to interpret this, but perhaps it's helpful.  

Edit: This is from a Readability web-to-epub conversion, which was then edited in Sigil.  I ran another epub through, removed some metadata, and it saved perfectly well.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Argument 'Start' must be greater than zero.
   at Microsoft.VisualBasic.Strings.Mid(String str, Int32 Start)
   at EPubMetadataEditor.Form1.SaveEpub()
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8009 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
EPubMetadataEditor
    Assembly Version: 1.3.19.0
    Win32 Version: 1.3.19
    CodeBase: file:///C:/Program%20Files%20(x86)/EPubMetadataEditor/EPubMetadataEditor.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.50727.8007 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Microsoft.VisualBasic/8.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8008 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8009 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8007 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8007 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8009 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8012 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
Accessibility
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8007 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Ionic.Zip
    Assembly Version: 1.9.1.5
    Win32 Version: 1.9.1.5
    CodeBase: file:///C:/Program%20Files%20(x86)/EPubMetadataEditor/Ionic.Zip.DLL
----------------------------------------
Microsoft.mshtml
    Assembly Version: 7.0.3300.0
    Win32 Version: 7.0.3300.0
    CodeBase: file:///C:/WINDOWS/assembly/GAC/Microsoft.mshtml/7.0.3300.0__b03f5f7f11d50a3a/Microsoft.mshtml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by benchen71** [comment]
Hi there,
You will need to send me the epub file that caused this error. Then I can
sort it out. Thanks!
Ben.

**Comment by ihopethisnameworks** [comment]
Hi Ben,

I'm attaching the epub.  I believe I mentioned in the edit that I saved the
epub in readability, used Sigil to remove the ugly cover page, and modify
some tags so it'd pass the FlightCrew test.  in Epub Metadata Editor I just
added authors and removed the Sigil tags from the .opf

I hope posting this error on GitHub was right.  First time, as I signed up
to GitHub merely for this because I'm quite grateful for this very nice
utility.  Thank you.

Be well,
Will

**Comment by benchen71** [comment]
Hi Will,
Only images can be attached here.  You can change the extension of the EPUB to .jpg and attach it.  Or just email it to ben dot chenoweth at gmail dot com.

**Comment by benchen71** [comment]
Hi Will,
I haven't heard from you in a while.  I am happy to take a look at your issue, but I can only do so with the EPUB.  I will have to close this issue soon if I don't hear from you.
Sincerely,
Ben.

**Comment by benchen71** [comment]
Can't confirm this bug without the EPUB, sorry.  Closing this issue now...

**Comment by Xavdidtheshadow** [comment]
Hey, getting the same issue here. just emailed you the epub!

**Comment by benchen71** [comment]
All fixed in version 1.4.11.

**Comment by Xavdidtheshadow** [comment]
Thanks! Great tool
