### ISSUE TITLE
Problem with Ionic.zip 1.9.1.8 + EPubMetadataEditorConsole 1.3.22.0

### ISSUE THREAD

**Issue by haudek** [benchen71/epub-metadata-editor#21]
This problem exist in version 1.3.23-1.3.25 (number whole package), maybe in 1.3.22 too.

Run EPubMetadataEditorConsole with ANY epub files, for example:
EPubMetadataEditorConsole.exe aaa.epub -extract Title

And then appears windows with error (GUI): 
--------------------------------------------------------------
Opis:
  Stopped working

Podpis problemu:
  Nazwa zdarzenia problemu:	CLR20r3
  Podpis problemu: 01:	epubmetadataeditorconsole.exe
  Podpis problemu: 02:	1.3.22.0
  Podpis problemu: 03:	559763f9
  Podpis problemu: 04:	EPubMetadataEditorConsole
  Podpis problemu: 05:	1.3.22.0
  Podpis problemu: 06:	559763f9
  Podpis problemu: 07:	11
  Podpis problemu: 08:	144
  Podpis problemu: 09:	System.IO.FileLoadException
  Wersja systemu operacyjnego:	6.1.7601.2.1.0.256.48
  Identyfikator ustawień regionalnych:	1045
...
--------------------------------------------------------------

AND additional error in console window:

--------------------------------------------------------------

Wyjątek nieobsłużony: System.IO.FileLoadException: Nie można załadować pliku lub zestawu 'Ionic.Zip, Version=1.9.1.5, Culture=neutral, PublicKeyToken=
edbe51ad942a3f5c' lub jednej z jego zależności. Zlokalizowana definicja manifestu zestawu nie odpowiada odwołaniu do zestawu. (Wyjątek od HRESULT: 0x80131040)
Nazwa pliku: 'Ionic.Zip, Version=1.9.1.5, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c'
   w EPubMetadataEditorConsole.Module1.OpenEPub()
   w EPubMetadataEditorConsole.Module1.Main()

OSTRZEŻENIE: rejestrowanie informacji o powiązaniach zestaww jest wyłączone.
Aby włączyć rejestrowanie błędw powiązań zestaww, ustaw wartość rejestru [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) rwną 1.
Uwaga: z włączeniem rejestrowania błędw powiązań zestaww wiąże się pewien spadek wydajności.
Aby wyłączyć tę funkcję, usuń wartość rejestru [HKLM\Software\Microsoft\Fusion!EnableLog].

--------------------------------------------------------------

Messages are in Polish, but enter "edbe51ad942a3f5c" in Google and you can get English messages.

With Ionic.zip 1.9.1.5 console wersion working OK, but then newest (1.3.25.0) GUI version not working and requires Ionic.zip 1.9.1.8.

**Comment by benchen71** [comment]
Acknowledged.  Version 1.3.26 will fix this.
