### ISSUE TITLE
What version of .NET is required? (Support .NET 4?)

### ISSUE THREAD

**Issue by WillItWork** [benchen71/epub-metadata-editor#22]
I've been testing this on a few different platforms, and using Win 8 and 10, with the built-in version of .NET 4 seems to cause to application to fail.

Are you using 3.5-specific features or is that a detection or protection issue?

**Comment by benchen71** [comment]
Actually, I am currently compiling with VB 2005.  Initially, this was to allow the program to work on older machines.  I thought that it still worked on Win 8, but must confess that I haven't personally tried it.

**Comment by benchen71** [comment]
I just checked and the program works fine on Windows 8.1.  So any failures you are experiencing are possibly to do with the EPUB file you are trying to open.
Since the program works on Windows 8.1 I am closing this issue.
