### ISSUE TITLE
Epub files are not opened

### ISSUE THREAD

**Issue by Gr3mar** [benchen71/epub-metadata-editor#23]
Epub files saved after the change are not opened by Adobe digital edition (win10) and Moon + Reader Pro (Android 4.1.2).
Probably a mistake with the compacting of the archive.
If I extract the epub files created, and compress them with another program, it works.
Test with epub-metadata-editor 1.4.5
rename jpg to epub
![volta](https://cloud.githubusercontent.com/assets/8766458/10122223/558e3638-6511-11e5-9ecf-e0224a894dd9.jpg)

**Comment by benchen71** [comment]
Issue confirmed.  I am uploading a new version (1.4.6) which works with ADE, so hopefully that fixes it.
