### ISSUE TITLE
Not saving after change

### ISSUE THREAD

**Issue by Sporitus** [benchen71/epub-metadata-editor#25]
Every time you press SAVE you got a alarm "File is ready-only"
Windows: 10

**Comment by benchen71** [comment]
If the file really is read-only, then close the program (losing any changes), right-click on the file and uncheck the read-only property.  Then open it in the program, make your changes and save.

However, if the program is somehow taking a non-read-only file and _making_ it read-only, then that's a problem!

**Comment by benchen71** [comment]
If there is still a problem, I can reopen this issue.  But I am closing it since I cannot replicate the problem.
