### ISSUE TITLE
Improvment request: File Renaming option

### ISSUE THREAD

**Issue by newargus** [benchen71/epub-metadata-editor#27]
Hello,

First, nice job ! I'm using your editor since 2 or 3 days, and it's working perfectly.

I've a request to improve sorting a lot of files with mixed author in the same directory: the possibility to combine file auto-renaming with directory creation and file moving such as with author name, (in fact with the same possibilities as file renaming rules). 

This could be a cool feature when you have tons of files to process. 

Olivier

**Comment by benchen71** [comment]
Hi Olivier,

It already does that.  In the "File renamer" setting window, use "\" to create subdirectories.  For example,

%CreatorFirstInitial%\%CreatorSurnameOnly% - %Title%

will move your files into folders according the the creator's first initial (of the surname).  This will work if you rename files individually, or in bulk using the "Batch Operations" panel.
