### ISSUE TITLE
Bug in EpubMetaDataEditor

### ISSUE THREAD

**Issue by akosak** [benchen71/epub-metadata-editor#28]
Hello,

I tried to change some metadata on my ebook. The editor saves something wrong, because after saving the changes, the book can't be opened anymore by other readers. I attached the ebook here as zip-file.

Greetings
A.K.

[ebook.zip](https://github.com/benchen71/epub-metadata-editor/files/1104191/ebook.zip)

**Comment by benchen71** [comment]
Hi A.K.,

The ebook in question has an empty date field and then a modified date field later.  At this stage, I don't think I can modify my program to handle such things.  However, it isn't hard to get around this problem:

1. Open the file in EPubMetadataEditor.  Don't make any changes yet.
2. Open the "Advanced Tasks" Panel (by clicking the long button on the right of the window).
3. Click the "Edit .opf file" button.
4. Find the line that looks like this:

`<dc:date opf:event=""/>`

and delete the whole line.
5. Click the "Save" button.
6. Make your changes to the metadata as per normal.
7. Save.

Hopefully, your file will still open in EPUB readers.

Sincerely,
Ben.
