### ISSUE TITLE
Batch Request Function

### ISSUE THREAD

**Issue by newargus** [benchen71/epub-metadata-editor#29]
It would be interresting to have a function to correct meta data fiels following end-user defined rules such as for the creator file as field to force to have space after comma or auto format between upper and lower case, to force field to defined value (language if missing) simular to file rename configuration. And to have it available by right-click on file (such as renaming)

**Comment by benchen71** [comment]
You can already "force field to defined value" using the "replace" option.  Check the box, and then click the "Field" link.  Choose, for example, the language field and then put what you want in the replacement box.

I will consider the other suggestions.  However, they sound like that would over-complicate the interface.  And the Batch Operations panel is already pretty complicated!

**Comment by newargus** [comment]
It's true for the replacement function is powerfull. I'm using it to correct some fields, but you can only correct one parameter (or more only if they have the same value) on each batch run. 

Than means, you need to open many times, to correct different values. I was thinking a default user-defined configuration that can also be available even after an application crash, when you restart the program (after you a not well formed epub file for exemple). 

For exemple, I'm have 99% of my epub in French. I'm using you program to correct, the Creator field and reformat the files. 

As Language is not the most important field, I'm not replacing it because it's a manual step to perform each time. 
If you have this replacement rule in some kind of "profile", running a batch renaming function for exemple could apply your default settings.

The same could be in your profile, to remember you decision, overwrite a file for exemple, can be decide at the first time and apply the same decision for the next files with the overwrite question.   

By the way, if you need a french translation for your interface, I can help ...

**Comment by benchen71** [comment]
I might be able to add metadata fields to the replace dialog.  When I get a chance, I'll run some experiments.

Thanks for the french translation offer.  However, the program was not written with internationalisation in mind.  It was just a tool that I wrote for myself and then released when I realised that others might find it useful, too.  To go back and convert everything to language strings is certainly _possible_, but it would be a huge amount of work!

**Comment by benchen71** [comment]
Hi newargus,
Well, it's not quite what you requested, but hopefully you can use the new features to do what you were wanting to do.  Check out 1.6.3 and see how you go!  For example, the new Find and Replace batch operation will be able to do things like adding spaces after commas.
But I don't think I will be able to add a saveable "profile".  I think it would be beyond my current programming abilities and available time!
