### ISSUE TITLE
content.opf corrupt

### ISSUE THREAD

**Issue by bertligtvoet** [benchen71/epub-metadata-editor#33]
When a meta tag (<meta ...>) is just before the end metatdata tag (</metadata>), the content.opt file becomes corrupt after saving the modified metadata.

I am bypassing this problem by placing the <dc language> tag just before the </metadata> tag with Sigil. After this change everything goes well with EpubMetatdataEditor.

Great application however, Thanks!

**Comment by benchen71** [comment]
Can you copy and paste into a comment here an example of an opf file which gets corrupted?  I'm not quite sure what you mean from your description.

**Comment by bertligtvoet** [comment]
I will provide you with an example looking for it.

 

 

Groet,

 

Van: Ben [mailto:notifications@github.com] 
Verzonden: vrijdag 23 februari 2018 22:51
Aan: benchen71/epub-metadata-editor <epub-metadata-editor@noreply.github.com>
CC: bertligtvoet <bert.ligtvoet@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [benchen71/epub-metadata-editor] content.opf corrupt (#33)

 

Can you copy and paste into a comment here an example of an opf file which gets corrupted? I'm not quite sure what you mean from your description.

**Comment by benchen71** [comment]
Until I get an example EPUB that displays the problem, I'm closing this issue.
