### ISSUE TITLE
epub size issue

### ISSUE THREAD

**Issue by edasis** [benchen71/epub-metadata-editor#34]
Since migration to ZipStorer file size changes a lot. I've done a test on random 5 epubs (no data added) and size increased by 15 percent.

v1.5.2:
7237.8 KB, 662.2 KB, 469.4, KB 626.9, KB 8783.0 KB
v1.6.5:
9399.0 KB, 710.3 KB, 519.3 KB, 709.2 KB, 9267.7 KB
org:
7237.8 KB, 660.7 KB, 468.3 KB, 626.6 KB, 8778.5 KB

**Comment by benchen71** [comment]
This isn't something that I can fix, unfortunately.  I had to use a Zip library that allows me to create an EPUB that is correct according to the specifications.  So size of output was not a consideration.
