### ISSUE TITLE
Problem when selecting the cover

### ISSUE THREAD

**Issue by adanak** [benchen71/epub-metadata-editor#35]
Hi!

First of all, thanks for your great software. It's very good!

I have some problem with this epub. If I try to edit the metadata, all is fine. But when I try to choose the cover picture and save, it crashes. Same thing if I try to prioritize the cover file.

Would you please check it out when you'll have some time?

Thanks a lot!
Pat

**Comment by adanak** [comment]
![test](https://user-images.githubusercontent.com/37123771/37072453-aa60a96a-218f-11e8-88fd-f50601065e3e.jpg)

There is the epub... Hope it works now...

**Comment by benchen71** [comment]
Got it.  Let me look into it...

**Comment by benchen71** [comment]
Fixed in 1.6.6.
