### ISSUE TITLE
Test file with error on Save

### ISSUE THREAD

**Issue by BeckyDTP** [benchen71/epub-metadata-editor#38]
Hello,

1. Get sample demo file:
http://www.nexto.pl/upload/sklep/kurhaus_publishing/ebook/dylemat_przelomowej_innowacji-joshua_gans-kurhaus_publishing/public/dylemat_przelomowej_innowacji-kurhaus_publishing-demo.epub

2. Try save file.

**Comment by benchen71** [comment]
Thanks for reporting.  I've worked out what's causing the problem and will hopefully upload a new version of the program tomorrow.
