### ISSUE TITLE
v1.6.3 breaks batch replacing fields with a blank string

### ISSUE THREAD

**Issue by DarkMatterMatt** [benchen71/epub-metadata-editor#40]
Loads of functionality added in 1.6.3, very nice 😄 unfortunately if I try to batch replace a field (or multiple fields) with a blank string it doesn't work (nothing changes).

You can compare changes between 1.6.2 > 1.6.3 here: https://github.com/benchen71/epub-metadata-editor/compare/1.6.2...1.6.3

**Comment by benchen71** [comment]
You're right. There's a lot of code in there that checks to make sure the user is not replacing with an empty string.  And yet there is _also_ a user dialog asking are you really sure you want to replace with an empty string.  So I have taken out the checks.

This means, of course, that the batch operation could now be used to strip all metadata out of every field if the user so chose.  Such power!  I trust it will not be abused.  I will not be held responsible... ;-)

(I'll get the updated version out later today, hopefully.)

**Comment by DarkMatterMatt** [comment]
Thanks, awesome fixing this so quickly :)
