### ISSUE TITLE
Cover detect for EPUB 3

### ISSUE THREAD

**Issue by BeckyDTP** [benchen71/epub-metadata-editor#41]
Proper cover image is not detected in EPUB 3 files.

Guide element is deprecated:
http://www.idpf.org/epub/301/spec/epub-publications.html#sec-guide-elem

Important is `cover-image` in manifest section opf file:
http://www.idpf.org/epub/301/spec/epub-publications.html#sec-item-property-values

Sample file:
[Sample_file_epub.zip](https://github.com/benchen71/epub-metadata-editor/files/3204310/Sample_file_epub.zip)

Please improve detect cover in EPUB 3 files, especially in the command line: `-extract cover`

**Comment by benchen71** [comment]
I'll take a look at this over the weekend.

**Comment by benchen71** [comment]
Had a chance to look at this tonight and made the change: try 1.6.12 and it will pick up cover information from the <manifest>. The command-line program has also been updated.

**Comment by BeckyDTP** [comment]
**1.6.12 is great for EPUB3. Thank you!**

I would be happy if the detection of the cover would also check existence the cover element in the metadata (EPUB2/EPUB3):
`<meta name="cover" content="id_of_cover_image" />`

If guide section is without "cover" element, "cover" in meta is an important place that should be checked when detecting the cover.

**Comment by benchen71** [comment]
The program was looking for "likely" cover ids.  But I have now added some code as a last ditch attempt (which should probably be a "first ditch" attempt now that I think about it!) which does what you have requested: it searches for "<meta name="cover"", retrieves the id, and then searches for that id in the manifest.

**Comment by BeckyDTP** [comment]
Yes, 1.613 is better, thank you!

I will ask for one more thing – reverse order in meta (_name_="cover" after _content_):
`<meta content="id_of_cover_image" name="cover" />`

**Comment by benchen71** [comment]
Done.  That was surprisingly a lot harder to do.  I've only lightly tested this so if you encounter any problems, please let me know.

**Comment by BeckyDTP** [comment]
It's amazing how much the program has been perfected in one day. 👍

I have the impression that the version 1.6.14 has improved detects covers only in the GUI version (command-line `-extract cover` result: `ERROR`).

**Comment by benchen71** [comment]
Can you attach an EPUB that generates an error?  I'll look into it...

**Comment by BeckyDTP** [comment]
Sure.

- John Smith - Sample File 2.0.epub
- John Smith - Sample File 3.0.epub
 

Additional file as sample divergence/mismatch data for cover in opf file.
- John Smith - Sample File 2.0 divergence.epub

This file has other cover declared in guide section and other in cover meta.
In such (very rare) cases, the program could inform about this fact. Why? Well, kindlegen uses data from the meta (when in guide section is xhtml file, not image), so the mobi file generated on the basis of such a "difficult case" will have a bad cover. I bought a file with this error in an ebook bookstore this year, so such a mistake may occur in the wild.

[test_files_for_command_line.zip](https://github.com/benchen71/epub-metadata-editor/files/3219635/test_files_for_command_line.zip)

**Comment by benchen71** [comment]
Turns out I neglected to include the updated version of the Console! So now I've updated the version numbers on both to 1.6.15.
I'm not going to be able to handle divergence files. That's something that will have to be handled by manually editing the opf file.

**Comment by BeckyDTP** [comment]
OK. Thank you.
[LastTestCommandLine.zip](https://github.com/benchen71/epub-metadata-editor/files/3220442/LastTestCommandLine.zip)

**Comment by BeckyDTP** [comment]
Just in case, two more files for testing (plus the one from the previous message).

[Sample file from bookstore](http://www.publio.pl/files/samples/d5/b8/b3/57459/Pan_Lodowego_Ogrodu._Tom_1_demo.epub)
Results:
`GUI: OK`
`Command line: ERROR`

[Free ebook](https://www.bibliopen.org/p/bopen/9780226300658) (Download ePub)
Results:
`GUI: ERROR`
`Command line: ERROR`

**Comment by benchen71** [comment]
Thanks for those.  I've found what was causing the problem in the Console version.  And I've now changed the cover processing order so that it the program starts by looking for <meta ... name="cover".  These changes probably warrant a bigger update, so 1.7.0 will come out tomorrow, if I have time to do some further testing.
