### ISSUE TITLE
Updating to 1.6.15 from 1.6.14 Stays on 1.6.14 (Possible Bug?)

### ISSUE THREAD

**Issue by arikinman** [benchen71/epub-metadata-editor#42]
I've downloaded the 1.6.15 file twice and tried upgrading as well as uninstalling/reinstalling this program to get it from 1.6.14 to 1.6.15, but it keeps saying it's at 1.6.14. The strange thing though, is that under my control panel, it says it is indeed 1.6.15. I'm not sure what's going on here, but I'm attaching screenshots of it.
![EPUB Metadata Issue -- 01](https://user-images.githubusercontent.com/22949542/58765810-b21f6280-852b-11e9-9c0e-702390dfa99d.png)
![EPUB Metadata Issue -- 02](https://user-images.githubusercontent.com/22949542/58765813-b6e41680-852b-11e9-832f-d834d2997818.png)

**Comment by benchen71** [comment]
Yeah, there's definitely something screwy going on.  I'll look into it and hopefully get a new version out soon...

**Comment by benchen71** [comment]
Hopefully version 1.7.0 won't have this problem!
