### ISSUE TITLE
Problem to open epub saved with epub-metadata-editor on microsoft edge

### ISSUE THREAD

**Issue by ottone100** [benchen71/epub-metadata-editor#45]
In this new version 1.7.3. When I apply cover fixes and save the epub, microsoft edge don't open the book, and return an error.

**Comment by benchen71** [comment]
I have confirmed the error. I will look into it when I get the chance.

**Comment by ottone100** [comment]
Thanks for your attention.
If it can help you, if I open the corrupted file from epub-metadata-editor with Sigil, the file is correct again. Perhaps the corrections made on the covers are not saved correctly by epub-metadata-editor. Another test I have done is that if I open the file corrupted by epub-metadata-editor with caliber it opens it. Only windows edge does not open it.
The fact is that windows edge is very convenient when you scroll through a list of ebooks with file browsing and want to quickly see a preview. I have found nothing better.
While epub-metadata-editor is the best solution to manage metadata and book covers in a simple and effective way.
