### ISSUE TITLE
Deleting changes

### ISSUE THREAD

**Issue by ellieroth** [benchen71/epub-metadata-editor#46]
I have a problem, I apparently aplied all the cover changes on the file but when I put on my reader and the cover doesn't appear I know for a fact that that can be fixed prioritizing the cover file, but that option doesn't appear anymore, is there a way to revert the process?

**Comment by benchen71** [comment]
You can do it manually by editing the opf file. But there isn't a button that does it automatically, sorry. You might try running the file through Calibre or Sigil and see if their EPUB reprocessing fixes the issue.

**Comment by ellieroth** [comment]
thank you, I'm gonna try those things,
