### ISSUE TITLE
Bulk edit ePub files (Also how to use Console)

### ISSUE THREAD

**Issue by L0garithmic** [benchen71/epub-metadata-editor#49]
I am just really wanting to bulk apply cover fixes and save. I can't figure out how to do it in Calibre and yours works so well. Could you make it so I can do it command line or drag and drop auto apply?

Edit1: or maybe you already have this with EPubMetadataEditorConsole. But there are NO guides on how to use it..

Edit2: So Found the commands for console, this really needs to be documented somewhere
`EPubMetadataEditorConsole.exe "filename" -extract <fieldname>

Available fieldnames:
 Title
 TitleFileAs
 Creator
 CreatorFileAs
 CreatorRole
 SecondCreator
 SecondCreatorFileAs
 SecondCreatorRole
 Series
 SeriesIndex
 Description
 Publisher
 Date
 Subject
 Type
 Format
 Identifier
 IdentifierScheme
 Source
 Language
 Cover
 Version`

However it seems all that does is extract info. I need to apply fixes, any possibility of adding that?

**Comment by benchen71** [comment]
I've now added the instructions for using EPubMetadataEditorConsole to the wiki (https://github.com/benchen71/epub-metadata-editor/wiki).

As you noticed EPubMetadataEditorConsole only extracts. It is a separate program (that admittedly utilises a good chunk of EPubMetadataEditor's code). But it doesn't contain any of the saving code. To add what you are asking for would be a seriously large addition, something I don't have the time for, sorry.

You can do bulk cover fixes using the Batch Operations panel though, so it's not too many clicks to process as many epubs as you want.
