### ISSUE TITLE
Portable Edition

### ISSUE THREAD

**Issue by L0garithmic** [benchen71/epub-metadata-editor#50]
Can you include a portable edition with your releases? It works just fine portable, I just install it, compress the folder, uninstall and copy the files. Could you consider just including a portable edition to save your users the time?

**Comment by benchen71** [comment]
Sure.
There's now a zip file in the Output folder: https://github.com/benchen71/epub-metadata-editor/blob/master/epubmetadataeditor/bin/Release/Output/EPubMetadataEditorNoInstaller.zip
