### ISSUE TITLE
Error unzipping file

### ISSUE THREAD

**Issue by Draecal** [benchen71/epub-metadata-editor#51]
Hi.

First time openning a book worked fine, but after a second attempt I'm receiving the following error: 

![image](https://user-images.githubusercontent.com/8697000/94255656-7b3f3e00-ff20-11ea-95f0-91f24caf1b92.png)

**Comment by benchen71** [comment]
Any chance you can attach the epub here?

**Comment by Draecal** [comment]
For sure.

[El mar de Fuego - Margaret Weis.zip](https://github.com/benchen71/epub-metadata-editor/files/5286441/El.mar.de.Fuego.-.Margaret.Weis.zip)

**Comment by benchen71** [comment]
That was weird. For some reason the zip library I use was throwing an error because of the datetime of the recently added cover files. I've added a work-around and it seems fine now.

**Comment by Draecal** [comment]
Happened again even after updating to the latest release.
[Las Chicas De Alambre - Jordi Sierra i Fabra.zip](https://github.com/benchen71/epub-metadata-editor/files/5304326/Las.Chicas.De.Alambre.-.Jordi.Sierra.i.Fabra.zip)

**Comment by benchen71** [comment]
The program throws the same error, but there is a different problem. I could not even open this epub with 7zip meaning that there is something seriously wrong with the file.

**Comment by Draecal** [comment]
Yeah, apparently, tried to open it with the reader and couldn't

**Comment by benchen71** [comment]
The next version will have more information in the error message so you can hopefully tell if the problem is with the file or with EPubMetadataEditor.
