### ISSUE TITLE
Recent rename schemes

### ISSUE THREAD

**Issue by Kryz-El** [benchen71/epub-metadata-editor#52]
This is not working as I had hoped. It rewrites a dropdown chosen scheme back to the list. Eventually I end up with 2 schemes repeated 3 times. Is there a way to only add previously unused schemes? Thanks again for your time on this.

I was thinking we could maybe have some more rename tokens? I would find %creator2fileas% , %creator2% and %subject% useful.

Thanks!

**Comment by benchen71** [comment]
Can do.

I'll try and get a new version out by the weekend.

**Comment by benchen71** [comment]
Check out 1.8.4. It should do what you are looking for.

However, it's not going to clean up the way things were before. So you might want to edit your settings file manually. Look for it in C:\Users\[Username]\AppData\Roaming\EPubMetadataEditor. Edit the ini file. Rearrange the items in the [Renamer] section:

[Renamer]
Template="%CreatorSurnameOnly% - %Title%"
Template5="(none)"
Template4="(none)"
Template3="(none)"
Template2="(none)"
Template1="%CreatorSurnameOnly% - %Series% - %SeriesIndex%. %Title%"

The Template item is the one that will be current when you open the Rename dialog. Delete the duplicates, and replace unwanted entries with "(none)".
