### ISSUE TITLE
big files

### ISSUE THREAD

**Issue by ellieroth** [benchen71/epub-metadata-editor#53]
is there a problem with files bigger than 2mb? 5 and up gets stuck loading

**Comment by benchen71** [comment]
It should be able to handle it. Can you attach the epub here? It might be some other issue.

**Comment by benchen71** [comment]
I'm closing this issue. The largest EPUB I have is 108 MB and it opens fine.

But there is almost certainly something going on with your file. If you upload it here, I can then do some bug tracking...
