### ISSUE TITLE
Release 1.8.6 seemingly corrupt

### ISSUE THREAD

**Issue by fylke** [benchen71/epub-metadata-editor#57]
Tried to run the 1.8.6 exe, but it said it couldn't run on my version of Windows (Windows 10)

Also tried the ZIP, but it says it's corrupt.

**Comment by benchen71** [comment]
Not sure what's happening on your machine, but I just downloaded and installed 1.8.6 from https://github.com/benchen71/epub-metadata-editor/releases/download/1.8.6/EPubMetadataEditorInstaller.exe successfully on a machine running Windows 10.

**Comment by fylke** [comment]
Huh, now that I tried again, it does install fine. I guess the download broke for me yesterday. Thanks!
