### ISSUE TITLE
REQ: Add previous and next button to edit the previous or next file in a directory

### ISSUE THREAD

**Issue by ArieKindicator** [benchen71/epub-metadata-editor#58]
Add a previous  and next button to save the current metadata of a book and open the previous or next book in a directory.
This should save a lot of time when editing the metadata of lots of books at once.

**Comment by benchen71** [comment]
I had a few minutes this evening and was able to add the buttons you requested. You'll find them on either side of the dropdown menu that displays all of the ebooks in the current directory. Expect the new version imminently...

**Comment by ArieKindicator** [comment]
Thanks, I made a small donation (*530).

**Comment by benchen71** [comment]
Thanks for that!
