### ISSUE TITLE
Adding “Series” and “SeriesIndex” destroys EPUB file.

### ISSUE THREAD

**Issue by Nakyoruto** [benchen71/epub-metadata-editor#59]
When trying out your program I noticed when I added “Series” and “SeriesIndex” information, my EPUB files get bricked and are no longer readable.

I used it on Manga EPUB file(s) in RTL format.

**Comment by benchen71** [comment]
You will need to provide an example EPUB which exhibits this behaviour. I usually find the problem is unrelated to what seems to cause it. I have added series and series index to many books without a problem.

**Comment by benchen71** [comment]
If you have trouble attaching am EPUB, change the extension from .epub to .jpg and upload it. It won't show up correctly, but I can rename it after downloading.

**Comment by Nakyoruto** [comment]
Here the files (1 source file and 1 modified)
https://we.tl/t-Tfgwc1pZK3

**Comment by benchen71** [comment]
I can see that that modified file has some issues in the <package and <metadata sections of the .opf file. I'll look into it when I get a chance.

**Comment by benchen71** [comment]
I think the problem has been fixed )see new version just released 1.8.8). It was caused by TAB characters being deleted during the regularising process. Now, they are getting replaced with a space and it seems to work fine. I have not extensively tested things, however.
