### ISSUE TITLE
REQ: (Batch operations) "Sequentialize all files into series" specify the Start number for Series Index

### ISSUE THREAD

**Issue by ArieKindicator** [benchen71/epub-metadata-editor#60]
The batch operation "Sequentialize all files into series" works excellent to add or change a Series title but the Series Index (Number) always starts with 1 (for the selected files). Obviously, this will suffice in most cases.

I have several book series containing over 200 book titles but they are not always complete. I want to add or update the Series Index number. As some book titles are missing, the automatic assignment of a series index number becomes out of sync.

Is it feasible to add an option where the starting number of "Series Index" can be specified manually?

**Comment by benchen71** [comment]
Yes, that should be relatively easy. The hardest part will be finding a place for another textbox!

**Comment by benchen71** [comment]
I've implemented your request. Check out the new version, 1.8.9.

**Comment by ArieKindicator** [comment]
Just to let you know. It works like a charm. Thank you.
