### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by kraummac** [benchen71/epub-metadata-editor#61]
Hello,
I've installed epub 1.89 yesterday to test it but this morning my antivirus has detected a malware ( HEUR:Backdoor.MSIL.Crysan.gen]  in it and has destroyed the program. I'm french and sorry but the message from kaspersky is in french
Please check
B.R
![Epub Metadata](https://user-images.githubusercontent.com/91784184/135713643-a73419ba-c960-418c-a68c-89d2c3a17f95.JPG)
![Epub Metadata-2](https://user-images.githubusercontent.com/91784184/135713703-d01a2d4f-f512-4d33-a244-1114d0799823.JPG)

**Comment by benchen71** [comment]
I'm not sure how to proceed with this. I haven't done anything different with the creation of the program. And as far as I know I don't have any malware running on my computer. I'm guessing it's a false-positive. Note that it says "HEUR", which indicates a heuristic search not an actual search: something in the executable looks similar to the malware.

I would suggest sending a message to Kaspersky getting them to look into it.

**Comment by kraummac** [comment]
Hi
thank you for your reply.
I will contact kaspersky about this issue and i keep you informed about
this issue..this could be long
B.R
