### ISSUE TITLE
Error when saving EPUB3 files in latest versions

### ISSUE THREAD

**Issue by Freekilll** [benchen71/epub-metadata-editor#62]
Hi, 

The latest version (1.8.9) is apparently messing the <package> tag in the .opf file when saving EPUB3 ebooks.

It adds `<package xmlns:opf="http://www.idpf.org/2007/opf" ...` instead of `<package xmlns="http://www.idpf.org/2007/opf" ...`. 

Note the **:opf** which AFAIK should be in the metadata tag but not the package one. Calibre (editor & reader) does not like that at all.

1.8.8 might do that too (haven't tested).  1.8.7 does not.

Edit : it  also affects non Epub3's

**Comment by benchen71** [comment]
Should be fixed in 1.8.10.
