### ISSUE TITLE
Replace tool not fully working as intended

### ISSUE THREAD

**Issue by TheCrappyCompletionist** [benchen71/epub-metadata-editor#64]
I tried replacing an entry in the batch edit mode with a blank string to clear it, but sometimes it put in random code, and sometimes it doesn't do anything. Sometimes it does clear the field, but most of the time it causes some random garbage to be filled in instead.

**Comment by benchen71** [comment]
I'll have to check this out. I know that dealing with empty strings is far more complicated than non-empty strings, because you often have to delete the OPF tags as well, rather than just replace existing content.

**Comment by TheCrappyCompletionist** [comment]
next time I get some long string or anything that isn't blank I'll post it here.

**Comment by benchen71** [comment]
What field were you trying to replace with an empty string?

**Comment by TheCrappyCompletionist** [comment]
I tend to replace multiple fields with empty strings - description, creator2, creator 2 file as, creator 1 file as, title file as etc.
