### ISSUE TITLE
Metadata batch edit breaking epub files

### ISSUE THREAD

**Issue by TheCrappyCompletionist** [benchen71/epub-metadata-editor#65]
This is actually related to the previous issue I've had that was marked as resolved - The metadata editor would give me an error as seen here:
[https://github.com/benchen71/epub-metadata-editor/issues/63](url)

but now I found out how the files are being corrupted. I'm batch editing the files, and the editor is breaking the package.opf file. 
I manually correct the error, but after batch editing it a second time, the file breaks again. Not sure why.
![image](https://user-images.githubusercontent.com/91967427/146668062-f8644926-fa9e-4283-8138-84d5c15fa5b3.png)
^ basically above was in correct format, but after pressing batch edit, the file broke again and now looks like this

**Comment by TheCrappyCompletionist** [comment]
more details: I'm trying to batch edit the following fields:
![image](https://user-images.githubusercontent.com/91967427/146668107-b45da93a-6133-4ff6-97ad-e882d44ebbf5.png)

**Comment by benchen71** [comment]
OK, it looks like something might be wrong when using the batch edit to replace Creator 2 with a blank string. I'll investigate...

**Comment by TheCrappyCompletionist** [comment]
Also, is there a way to batch edit the creator 1 and 2 type? like set them to author/illustrator etc.?

**Comment by benchen71** [comment]
I've confirmed the error: the code is not handling multiple creators with EPUB3 files correctly when replacing fields with an empty string.

**Comment by benchen71** [comment]
I think the problem has been dealt with. And as a bonus for waiting for patiently, I've also added the ability to batch set the creator1 and creator2 roles! Check out 1.8.11.
