### ISSUE TITLE
Unable to save creator as illustrator

### ISSUE THREAD

**Issue by TheCrappyCompletionist** [benchen71/epub-metadata-editor#66]
I've tried batch edit and single edit, I can't seem to save creator 2 as an illustrator.

**Comment by benchen71** [comment]
The code I changed only applies to EPUB3s. Is the EPUB you were editing an EPUB3? You might want to do the "change extension, upload as jpg" trick again...

**Comment by benchen71** [comment]
I just checked with an EPUB2 and it doesn't work unless you include something in the "File as" box. I can fix that, I think.

**Comment by benchen71** [comment]
You can save an EPUB3 with a Creator2 role without putting something in the "File as" box. So the problem just affects EPUB2s.

**Comment by benchen71** [comment]
I've fixed the code. But I'm not sure when I will have time to put out a new release. In the meantime, as a workaround, just make sure you include a "file as".

**Comment by benchen71** [comment]
I just went ahead and released 1.8.12. Hope that's it!

**Comment by TheCrappyCompletionist** [comment]
I've tried with all my epubs, but they're a mix of EPUB3 and EPUB2. Not sure what is causing it...
