### ISSUE TITLE
Unable to set Creator2 role

### ISSUE THREAD

**Issue by TheCrappyCompletionist** [benchen71/epub-metadata-editor#67]
The patch fixed the problem for single-file edit for EPUB2, but the issue still persists for batch edit for both EPUB3 and EPUB2, and solo edit for EPUB3.

**Comment by TheCrappyCompletionist** [comment]
I can add a role with a "file as" entry, but if left blank, it's not possible.
(I don't fill a file as because I have no idea what it is)

**Comment by benchen71** [comment]
You will have to supply some examples. The code worked fine with every EPUB I threw at it.
"File as" provides EPUB viewers with how you want them to sort your books. So, for example, if the author is "Alexander McCall Smith", I would provide a "File as" of "McCall Smith, Alexander".

**Comment by TheCrappyCompletionist** [comment]
After further testing:
EPUB3
Unable to set both Creator 2 file as and role, both batch and single edit

EPUB2
Unable to set creator 2 file as and role in batch edit

**Comment by TheCrappyCompletionist** [comment]
every epub I threw at the editor behaved like this

**Comment by TheCrappyCompletionist** [comment]
After doing even further testing - it seems like creator2 file as is being edited in the file, but not being displayed in the editor. creator 2 role is still not being edited. (EPUB3)

**Comment by TheCrappyCompletionist** [comment]
seems like there is no real consistency to this problem anymore. Sometimes the details get changed, sometimes they don't. What I've been doing is manually editing them single-file, and if it doesn't change in the editor I manually change the details by unpacking and editing the content file myself. 
I've also  had a few epubs where I edit the content file, and repack it back into an epub, but the editor doesn't see or list the changes I made.

**Comment by benchen71** [comment]
Seems like the recent changes may have made things worse. I don't have time at the moment to look into it. You might need to revert to an earlier version?

**Comment by TheCrappyCompletionist** [comment]
don't worry about getting this resolved quickly, I'll just try to figure out some consistency to the issue to make it easier for you to debug :)

**Comment by benchen71** [comment]
You might need to explain more clearly what you are trying to do and how you are trying to do it. I just ran a test with three EPUB2 files. They did not have a second creator. I used the batch "Replace" function to add a Creator2. I then did a second batch "Replace" function to add "ill" to Creator2. It all worked fine: the three files now have a Creator2, with no "File as", and illustrator as the role. I then did the same thing with three EPUB3 files and again it worked as expected.

It is possible that the program is not able to do this properly if there are errors in the OPF file (possibly left there by an earlier version of the program).

Also, I should point out that you can manually edit the OPF file from inside EPUBMetadataEditor. Just click the "Edit .opf file" button in the Advanced Tasks area of the Batch Operations panel. Any changes you make in the editor window should be saved when you click "Save", and the interface should also update to show the changes made. I use this window to clean up OPF file errors.

**Comment by TheCrappyCompletionist** [comment]
![image](https://user-images.githubusercontent.com/91967427/147845150-cc7b2e05-f0c6-4e2a-a9e0-bca930c4e851.png)
I've tried manually editing the "file as" and role in this menu here. After saving and re-loading the file, the fields are empty. 
I've also tried using the replace function, but it had the same effect, leaving the fields empty when I reload the file. 

![image](https://user-images.githubusercontent.com/91967427/147845164-1a228c84-8b33-40d4-a449-3692e8a046ea.png)
This is how the opf file looks - I can't really make much sense of it because technically, both creators should have the same format, right? I'm not familiar with the formatting, but from what I can see, creator 1 is formatted one way, while creator 2 is formatted differently.

**Comment by benchen71** [comment]
I don't know how the file got like that, but it appears to be mixing up how EPUB2 and EPUB3 handle the extra info.

In an EPUB2 file, it should look like:
<dc:creator opf:file-as="Akata, Itsuki" opf:=role="ill">Itsuki Akata</dc:creator>

In an EPUB3, it should look like:
<dc:creator id="creator2">Itsuki Akata</dc:creator>
<meta refines="#creator2" property="file-as">Itsuki Akata</meta>
<meta refines="#creator2" property="role" scheme="marc:relators">ill</meta>

**Comment by TheCrappyCompletionist** [comment]
> 

Can confirm - the new update broke the application lol. Tried batch editing fresh epubs, the whole file is corrupted now:
![image](https://user-images.githubusercontent.com/91967427/147846303-527c6ee5-6ee0-4884-aece-9815067b4e2d.png)
I'll revert to the old version and try again

**Comment by benchen71** [comment]
It's very hard for me to track down bugs like this. Can you please post a problematic file to this chat. You also need to tell me what you are trying to do with the batch operations panel.

**Comment by TheCrappyCompletionist** [comment]
I'm currently using the older version - 1.8.11, because it seems like 1.8.12 is more broken than 1.8.11
I'll try to find a consistent way to trigger the issue, and update you here.

**Comment by TheCrappyCompletionist** [comment]
Using 1.8.11: I ran batch edit 5 times. 
- replace Creator 1 and file as with "FUNA".
- replace Creator 1 role with "aut".
- replace Creator 2 with "Itsuki Akata"
- replace Creator 2 file as with "Akata, Itsuki"
- replace Creator 2 role with "ill"
(EPUB2)
This is the result in the OPF file:
![image](https://user-images.githubusercontent.com/91967427/147846520-2ae5fa42-cc5f-4685-9094-8f94c0c2a4c8.png)
This is what shows up in the editor:
![image](https://user-images.githubusercontent.com/91967427/147846526-155ee925-f605-45aa-9162-6045b9e0850d.png)

(EPUB3)
This is the result in the OPF file:
![image](https://user-images.githubusercontent.com/91967427/147846547-ca15b3bc-4529-41f6-8c81-3f8c95bde5fd.png)
This is what shows up in the editor:
![image](https://user-images.githubusercontent.com/91967427/147846537-ce441661-2a20-4ae8-9685-d9318a89be78.png)

**Comment by benchen71** [comment]
That's the problem right there. The old version's batch operation neglected to check whether the file was EPUB2 or EPUB3. The new version (1.8.12) does check. I'm afraid the older version has messed the OPF files up, and the new version is not able to handle them successfully.

**Comment by TheCrappyCompletionist** [comment]
I tried using the new version to edit clean files, but it corrupted them somehow, not sure what went wrong there. I did the same operations as I described up top, making 5 batch edits, and the result is that image filled with 0's in the OPF file.

**Comment by TheCrappyCompletionist** [comment]
This is what I do from start to finish:
- replace all fields except title and title as with blank.
- turn all files into a series using the other tool
- replace the title and title file as with "%series% - Volume %seriesindex%"
- replace creator1
- replace creator1 file as
- replace creator 1 role
- replace creator 2 
- replace creator 2 file as
- replace creator 2 role

**Comment by benchen71** [comment]
Once the OPF files are corrupt the program isn't going to be able to fix them. That would have to be done manually. You will need to manually edit each OPF file (which, as I mentioned above, can at least be done inside the program without needing to use a ZIP manager) and remove any problematic XML. Once the files are cleaned, you could try to use the newest version to add the metadata back in.

**Comment by TheCrappyCompletionist** [comment]
This is how the raw file is when I first recieve it:
![image](https://user-images.githubusercontent.com/91967427/147847384-6b697f7d-98a9-4890-9ec5-efedbab66387.png)
(EPUB3)
Is the editor able to correct any errors in this?

**Comment by benchen71** [comment]
I don't see any errors. If you put that through the newest version, it should work. If it _doesn't_ then something else might be going on and I would need a copy of the original (unedited) file to experiment with.

**Comment by TheCrappyCompletionist** [comment]
Before:
![image](https://user-images.githubusercontent.com/91967427/147847682-5912d18a-fe31-4c1e-b2b7-30ec7d2b3e36.png)
After:
![image](https://user-images.githubusercontent.com/91967427/147847671-bb83395b-f722-4854-b205-190f64157e12.png)

I did the standard steps, and after I was done, the creator fields that I filled out didn't work. 
![image](https://user-images.githubusercontent.com/91967427/147847688-5c2e5509-88d5-40cf-9f61-fe4240c00a03.png)

**Comment by benchen71** [comment]
But that is an EPUB2. In the package tag, it says version="2.0". The previous screenshot said version="3.0". Did something happen between?

But then my program appears to have handled the file as an EPUB3, however. Were you using the most recent version (1.8.12)?

I am super confused. Will you post the original EPUB file here? We will go back and forth forever at this rate!

**Comment by TheCrappyCompletionist** [comment]
sorry for the confusion - the post above is a completely different file. I'm using the newest version, and I did my standard steps as described above, where I clear everything then use teh replace tool to add the metadata. 
It seems like the program handles the file as an epub3 despite it being an epub2.

**Comment by benchen71** [comment]
Can you please attach the epub2?

**Comment by benchen71** [comment]
Actually, you don't have to. I've run a test with one EPUB3 and one EPUB2 and I can confirm the error. I will look into it.

**Comment by benchen71** [comment]
Here's a pre-release version 1.9.0. Download the "image" file to your computer, and then change the extension from jpg to exe. You can then test to see if the batch edit now correctly switches between EPUB2 and EPUB3 successfully. (It did with my quick test!)
![EPubMetadataEditor](https://user-images.githubusercontent.com/6054381/147848227-0c743783-36ce-4b88-b1d2-9ed678f428e2.jpg)

**Comment by TheCrappyCompletionist** [comment]
I'm unable to download the image... idk maybe because I'm using opera
I'm not really sure how you download it, but the option to save the image is greyed out

**Comment by TheCrappyCompletionist** [comment]
seems like 1.9.0 worked just fine, thanks!

**Comment by TheCrappyCompletionist** [comment]
actually, I'm trying this on another epub3 from a different series, I'm not sure if it's the file or the editor. I'll try ediitng it and seeing the OPF file

**Comment by benchen71** [comment]
It definitely look like something has gone wrong during the processing. If you attach the original EPUB to this chat (after changing the extension to jpg) I can give it a look. What were you trying to edit, metadata-wise?

**Comment by TheCrappyCompletionist** [comment]
I was trying to edit my standard fields - clear everything, then change creator 1 and 2, title and series and index.
The file is too big to upload here, so I've put it on my drive: https://drive.google.com/file/d/1DTkZkDHFSgR8CNgqyMpJ3abrU5o5bnQA/view?usp=sharing

**Comment by benchen71** [comment]
I'll take a look at it tomorrow. It's bedtime here in Australia. (By the way, I tried to access the file and I had to request access, which  I have now done...)

**Comment by benchen71** [comment]
I've found a couple of bugs, which I have attempted to fix. You can try this updated pre-release 1.9.0:
![EPubMetadataEditor](https://user-images.githubusercontent.com/6054381/147862417-4b8462be-247d-434d-95cc-75eeff1b6e2c.jpg)
I should point out that by replacing fields in an EPUB3 with empty strings the program will leave "<meta refines" lines that are no longer needed. These would be almost impossible to remove programmatically, unfortunately. It would be far better simply to replace the existing content with the new content without first replacing with the empty string.

**Comment by benchen71** [comment]
Actually, I think there is another bug, depending on how the Creator2 refines have been labelled. Look for an update later today...

**Comment by TheCrappyCompletionist** [comment]
I'm not quite sure the file is supposed to look like this...
![image](https://user-images.githubusercontent.com/91967427/147863459-3887fd9a-7830-4c81-a30f-d382e7e71a87.png)
This is how the OPF looked beforehand
![image](https://user-images.githubusercontent.com/91967427/147863465-dc00dfa3-0772-4b3f-9b9d-f0fb95b296ec.png)

As you said, there could still be a bug for when the creator gets added.

**Comment by benchen71** [comment]
Wow, that's a mess! Was that with generated by the version in the post a couple of posts above this one?

**Comment by benchen71** [comment]
OK, here's what I am hopeful is a fully-working version. If anything fails this version, you'll need to give me access to it.
![EPubMetadataEditor](https://user-images.githubusercontent.com/6054381/147865012-12e42ddd-3dfc-4a7f-a910-baecbdc93b09.jpg)

**Comment by TheCrappyCompletionist** [comment]
I've tested the new version, and there seems to be some weird behaviour. 
I correct the corruption in the OPF file, then proceed to copy creator 1 to creator 1 file as. 
save.
I copy creator 2 to creator 2 file as. 
save.
reload.
creator 1 file as is corrupted.
when I try to re-copy creator 1 to file as, once I save and reload, creator 2 file as corrupts.

**Comment by TheCrappyCompletionist** [comment]
first I edit the OPF until it's like this
![image](https://user-images.githubusercontent.com/91967427/147866195-0a0d516f-a14c-47fd-b41d-372b3b67cc9c.png)
the editor shows blank fields after saving and reloading.
![image](https://user-images.githubusercontent.com/91967427/147866200-3bd94770-3d75-46dd-836f-c7350064c756.png)
I add creator 1's details.
![image](https://user-images.githubusercontent.com/91967427/147866213-28af5e62-9bd8-44d5-93a9-895a6756b830.png)
![image](https://user-images.githubusercontent.com/91967427/147866216-575fa174-6f26-4282-bb4d-53bd9e579e02.png)
I add creator 2's details.
![image](https://user-images.githubusercontent.com/91967427/147866222-c044be92-2baf-44f6-8fa1-262d0985d2b2.png)

After saving and reloading, the file looks like this:
![image](https://user-images.githubusercontent.com/91967427/147866229-9505e2fc-ee9f-4155-bb67-434989033d03.png)
![image](https://user-images.githubusercontent.com/91967427/147866233-32fa45a8-620d-43fd-872a-c28fe13d325a.png)

**Comment by benchen71** [comment]
I think I've got it. This has been some difficult bug squashing! Try this updated version:
![EPubMetadataEditor](https://user-images.githubusercontent.com/6054381/147870080-716d9fec-1c1c-4398-b7be-7cb46a085c8f.jpg)
Let me know how you get on.

**Comment by TheCrappyCompletionist** [comment]
I've tested it on all epubs and it works beautifully, thanks so much!
Hope I didn't cause you too much headaches with my terrible explanation and bugtesting 😅

**Comment by benchen71** [comment]
Actually, you've been very helpful! Normally, when I do an update I don't do a whole lot of testing. If it works with one or two of my books, I'm happy. So I appreciate: 1) you reporting the bugs in the first place, and 2) all the testing you've been doing!

**Comment by TheCrappyCompletionist** [comment]
Guess it's thanks to my OCD not being happy with my books having "similar" titles, they have to all be the same, and all the metadata has to be the same too 😛
