### ISSUE TITLE
unable to edit creator 2 file as (EPUB2)

### ISSUE THREAD

**Issue by TheCrappyCompletionist** [benchen71/epub-metadata-editor#68]
Oh boy, here we go again...
It seems like the editor is incorrectly editing the Creator 2 file as for EPUB2.
![image](https://user-images.githubusercontent.com/91967427/147874409-a696f274-1a7e-4258-ba58-3511861c75f1.png)
I've tried batch editing and single-file editing, it seems to be busted. 
(pre-release version 1.9.0)

(ngl I kinda feel terrible for pestering you with these bugs)

**Comment by benchen71** [comment]
I'll need to see the whole EPUB... :-)

**Comment by TheCrappyCompletionist** [comment]
Here's the before and after for another epub2 example.
before:
![image](https://user-images.githubusercontent.com/91967427/147924096-60b88f61-0519-4652-aa20-5d0adfa8f3d9.png)
![image](https://user-images.githubusercontent.com/91967427/147924198-88c01276-a716-40c4-9355-5eb5b8fee79c.png)
after:
![image](https://user-images.githubusercontent.com/91967427/147924130-92c67f05-3b31-4509-b535-5a16a80b301e.png)
![image](https://user-images.githubusercontent.com/91967427/147924179-660214d2-b27d-4499-b9c1-4a854b667e90.png)

all i did was add the creator2, file as and role. Seems  like the editor is adding the metadata in the epub3 format. 
Unless you meant you want a link to the epub itself?

**Comment by benchen71** [comment]
These sort of problems can sometimes be caused by non-standard opf files, or things that might be allowed, but are different to the way my program handles it. So, yes, I will need to download the EPUB in question. Thanks.

**Comment by TheCrappyCompletionist** [comment]
![Drugstore in Another World - LN 01](https://user-images.githubusercontent.com/91967427/147928817-45a6e47e-9bee-403e-9041-02043e51ee2b.jpg)
wow finally an epub that is small enough to upload :|

**Comment by benchen71** [comment]
I can confirm the error. Now to try and work out what's going wrong...

**Comment by benchen71** [comment]
I think that some of the EPUB2 code got deleted during a recent bug fix. So I've had to completely restructure the EPUB save code as far as the creators are concerned to make it more logical and consistent. (This program well and truly predates EPUB3s and I remember when the new standard came out I worried that the initial code changes were not well thought out!)

From what I've seen so far, the new code is holding up under testing. However, given the amount of changes that have been made, please do not use this test version on EPUBs that have not been backed up!

![EPubMetadataEditor](https://user-images.githubusercontent.com/6054381/148027901-7eaa9347-0ed7-49ad-95e8-eec94d69b2cb.jpg)

**Comment by TheCrappyCompletionist** [comment]
so far I've re-edited multiple book series and the editor seems to be working just fine now. 
I have noticed that the metadata seems to include some minor formatting hiccups, like an additional bracket.
![image](https://user-images.githubusercontent.com/91967427/148033554-b925c7da-6841-42a3-b6a0-ac73bd673d38.png)
![image](https://user-images.githubusercontent.com/91967427/148033642-cd1f7295-6992-4d4f-be04-d50e6af5e845.png)
![image](https://user-images.githubusercontent.com/91967427/148033750-fa745351-b828-47c9-a624-a28476adea1e.png)

**Comment by benchen71** [comment]
I will investigate fruther. It might be dependent on how end of lines are being handled. Some EPUBs use one character, some use two. Either way, those double brackets will break Calibre.

**Comment by TheCrappyCompletionist** [comment]
I just mass edited over 75 epubs at once and it seems to work fine beside that hiccup. most of them were epub3s. looking real good, seems like this is almost over 👍

**Comment by benchen71** [comment]
Here you go. This one is looking good!
![EPubMetadataEditor](https://user-images.githubusercontent.com/6054381/148048454-030c9646-0c42-4041-a6bd-fb7c650e1afa.jpg)
(The only difference to the previous one is with the handling of second creators in EPUB2s.)

**Comment by TheCrappyCompletionist** [comment]
![image](https://user-images.githubusercontent.com/91967427/148057489-d3685b15-2a5e-45f6-b444-21f94a551403.png)
seems like it's all good now! I'll still have to manually correct the slight corruptions, but from what I tested, new epubs got edited just fine. thanks so much! :)

**Comment by benchen71** [comment]
Yes, once the corruption has set in, there isn't anything you can do but edit the OPF file manually. That's why I recommend making a backup of your EPUBs before editing them, at least until we can be sure the code is working as it should.

But it's looking good! Most of the code was old code that I moved into a more logical order, so it should be OK. I will release 1.9.0 officially now...
