### ISSUE TITLE
Allow font change in UI

### ISSUE THREAD

**Issue by w64bit** [benchen71/epub-metadata-editor#73]
Please add the option to change font to UI.
Example: Verdana 8. It's wider and allow easier selection/editing in boxes.
The ony thing is to create the space on UI and buttons to allow wider font.
Maybe using MS Shell Dlg 2 instead MS Shell Dlg will solve this issue.
Thank you

**Comment by benchen71** [comment]
This is beyond my programming experience, sorry.
