### ISSUE TITLE
[BUG?] "belongs-to-collection" metadata in epub3 is not used (preventing some software from creating series)

### ISSUE THREAD

**Issue by VegethB** [benchen71/epub-metadata-editor#74]
When an epub3 is edited, the "series" and "series_index" fields are inserted as in the example below.
(Even using the batch mode)

This software:

```
      <meta name="calibre:series" content="Monogatari Series"/>
      <meta name="calibre:series_index" content="1.0"/>
```
<details>
 <summary>screens:</summary>

![Inked194876788-eda4eb26-0e78-4153-a442-3d562ec6aa46](https://user-images.githubusercontent.com/17975351/194879479-e80a1e56-365c-4e51-b88d-c4018296f99c.jpg)

</details> 

 Unfortunately this prevents certain software from creating the series view.
I am referring specifically to the Kavita software.

https://wiki.kavitareader.com/en/guides/managing-your-files/ebooks

 Editing the same epub with Caliber, it seems that the correct tag/metadata for the epub3 is used which is recognized by the software (Kavita) and then creates the series in the software.
 
  Calibre edit:

```
    <meta property="belongs-to-collection" id="id-3">Monogatari Series</meta>
    <meta refines="#id-3" property="collection-type">series</meta>
    <meta refines="#id-3" property="group-position">1.0</meta>
```

<details>
 <summary>screens:</summary>

![image](https://user-images.githubusercontent.com/17975351/194874906-9f0b04d2-46b9-4283-8cc0-dbed060c70e8.png)
![image](https://user-images.githubusercontent.com/17975351/194874969-77156172-56fc-4c29-a59b-d461893570a7.png)
![Inked194875286-f06cb78d-4c21-4ba8-a9f8-99e9becb1628](https://user-images.githubusercontent.com/17975351/194879428-3e65b40c-b8ab-49ef-b6ca-6deb3fb27c15.jpg)

</details> 

Starter e-book
![Monogatari Series - Volume 01 - Bakemonogatari (Part 1)  Vertical](https://user-images.githubusercontent.com/17975351/194881219-f6d8c8cd-8e3f-464c-8ff2-5746b7e05abe.jpg)
![Monogatari Series - Volume 01 5 - Bakemonogatari (Part 2)  Vertical](https://user-images.githubusercontent.com/17975351/194881508-6ca285df-0630-4da7-9610-8d42af200abe.jpg)

**Comment by benchen71** [comment]
The way EPUB Metadata Editor implements series dates from EPUB2 days and followed Calibre's method of the time. But I have not updated this code for EPUB3. To be honest, it would be a lot of coding for very little result. I don't have as much coding time as I used to, sorry!

**Comment by benchen71** [comment]
The new version will include the EPUB3 way of handling series information.
