### ISSUE TITLE
Bug(?) empty subject meta data

### ISSUE THREAD

**Issue by docjc** [benchen71/epub-metadata-editor#75]
after using epub-metadata-editor and changing some words eg in title the program is creating an empty subject field at the end of the metadata without haveing edited anything in this field. Is it possible to change this behaviour? It would be better not to create an empty subject (This causes my softwre to get problems ;))

**Comment by benchen71** [comment]
I guess it should be possible. But there are a few different scenarios to consider (for example, that there has been a subject but the user has cleared that box). And I don't have as much programming time as I used to!

**Comment by docjc** [comment]
Hi,
its a pity that you have not the time to “repair” the code 😉 cause I like this program, it is just what I’m looking for

attached you’ll find 2 examples of the meta part of a content.opf file, before and after editing with your program I changed only the yellow line but 2 other things happened: the subject line was added (red), empty, and the light blue part was deleted.   

So 3 questions: 

 

*	If you add the subject line shouldn’t it read correctly:  <dc:subject>< /dc:subject>?
*	Why adding this line?
*	Why deleting the description?



 

 

Von: Ben ***@***.***> 
Gesendet: Montag, 31. Oktober 2022 06:05
An: benchen71/epub-metadata-editor ***@***.***>
Cc: docjc ***@***.***>; Author ***@***.***>
Betreff: Re: [benchen71/epub-metadata-editor] Bug(?) empty subject meta data (Issue #75)

 

I guess it should be possible. But there are a few different scenarios to consider (for example, that there has been a subject but the user has cleared that box). And I don't have as much programming time as I used to!

**Comment by benchen71** [comment]
If you want to add images, you have to do it directly on the GitHub site. I would like to see the images, though. If there is a bug, I will endeavour to fix it.

**Comment by docjc** [comment]
Hi,
here the Pdf
[EME.pdf](https://github.com/benchen71/epub-metadata-editor/files/9907996/EME.pdf)

**Comment by docjc** [comment]
Hi,
here  is the test.jpg as requested
![test](https://user-images.githubusercontent.com/108517885/199225730-c022c1fd-941d-438b-bc85-b5c490015e2a.jpg)

**Comment by docjc** [comment]
I forget to mention, test.jpg is untouched

**Comment by benchen71** [comment]
I've downloaded the file (and edited the comment to remove it).

**Comment by benchen71** [comment]
Thanks for your patience. I've made a small change to the subject creation code, so that an empty subject field won't be added. Hopefully, that solves the problem. That said, your screenshots show that the description was getting deleted. That looks like a serious bug; but I was not able to replicate it with the most recent version of the program. If you find something like that happening, please add another issue (including EPUB files changed to JPGs).

**Comment by docjc** [comment]
nice to hear from you..... (I know how difficult it is sometimes to have a hobby besides work and family - so don't worry.)
I will test the new version and come back 
Thank you
