### ISSUE TITLE
Series name and index number are 'reversed'

### ISSUE THREAD

**Issue by jaqarll** [benchen71/epub-metadata-editor#77]
Hi,

first of all thanks for this great tool. I've been using it a lot in the recent days due to having a new pocketbook ereader, however, I encountered an issue with either this tool or pocketbook in the way series are handled.

When I inlcude series information in an epub it seems to get inserted into the metadata like this:

    <meta name="calibre:series_index" content="3"/>
    <meta name="calibre:series" content="X"/>

This results in my reader finding the series, but not being able to add the series number. If I manually switch the spots, so the series name comes before the number it works.

Should, logically, the series Name not come first anyway? I could also contact pocketbook about it, but I thought I'd try it here first.

I'm currently editing all the files by hand.

**Comment by benchen71** [comment]
The thing with XML is that tags can come in any order. So this is definitely a problem with the reader.

**Comment by jaqarll** [comment]
Too bad, my hope for them fixing it is slim, but I have informed them at least.
