### ISSUE TITLE
Virustotal reports security vendors flagged the executable file as malicious

### ISSUE THREAD

**Issue by mike-lowski** [benchen71/epub-metadata-editor#78]
https://www.virustotal.com/gui/file/14a2f1c100a8a376e6027813657a877efc09c8a4137f4323af2e16ed1ea6b7d4/detection
https://www.virustotal.com/gui/file/1f6859e2dde010fc79949cddc8bf7d2ca34ba089f78f2382cfd7016d42ff0f0a/detection
https://www.hybrid-analysis.com/sample/14a2f1c100a8a376e6027813657a877efc09c8a4137f4323af2e16ed1ea6b7d4

**Comment by benchen71** [comment]
There's nothing I can do about this. There is definitely nothing malicious about the installer or the program's executable. But you will have to take my word for this over the security vendors.
