### ISSUE TITLE
Can't save a cover to an epub3 file

### ISSUE THREAD

**Issue by LadyHaywood** [benchen71/epub-metadata-editor#79]
When trying to add a cover I would get an error saying it can't find the file. However, when you open the file contents there is a cover image file and a coverpage xhtml file but it won't apply that cover. Moving the book over to my ereader or in calibre the cover just doesn't show at all.
I've also tried using an image from the book just don't work. It'll blink but nothing would happen.

**Comment by benchen71** [comment]
You'll have to attach the file, because there will probably be something else going on. If you change the extension from .epub to .jpg you will be able to attach the file here. I can then change the extension back at my end.

**Comment by LadyHaywood** [comment]
I'm not able to add it since it's over the 10MB limit. I've never tried compressing an epub further or an epub turned image file before so I don't know if I'm able to do that. Is there another way to send the file?

**Comment by benchen71** [comment]
Email it to me: ben dot chenoweth at gmail dot com

**Comment by LadyHaywood** [comment]
Sorry for the wait, I've sent an email about the file.

**Comment by benchen71** [comment]
Sorry that it has taken me so long to get back to you. Essentially, as far as I can tell the problem exists with the EPUB file itself. There are two xhtml files missing, including the one that is the fallback cover page. If you open the "Advanced Tasks" panel, you can then edit the .opf file. Then in the <guide> section near the very bottom of this file it says this:

  <guide>
    <reference type="cover" title="Cover" href="page00001.xhtml"/>
    <reference type="text" title="Start" href="page00002.xhtml"/>
  </guide>

But there are no pages with either of these names in the EPUB itself, which you can also verify by clicking the "Show EPUB contents in Windows Explorer" button. The reason the other file you supplied does show a cover correctly is that the page listed as the cover is present in the EPUB.

I don't think it is possible for me to get my program to fix this issue. You would have to manually edit the EPUB file. I would suggest copying page00001.xhtml from the file that works and then editing it to match the cover filename. Then, hopefully, it will open correctly!

**Comment by benchen71** [comment]
Actually, you can simply rename coverpage.xhtml to page00001.xhtml. It's in the OEBPS folder after you click the "Show EPUB contents in Windows Explorer" button. Then return to EPUB Metadata Editor and save the file. When you close and re-open it, it should work correctly.
