### ISSUE TITLE
Last Window position

### ISSUE THREAD

**Issue by WelshSpringer** [benchen71/epub-metadata-editor#80]
Many thanks for a really useful tool. 

It would be great if EPub Metadata Editor could remember its last position on the screen when reopening; it's a nuisance having to move the window to a more convenient location every time.  If there's already an option for this, apologies, but I couldn't find it.

Alternatively, please centre the window on the screen rather than allowing it to open in a random place.

Thanks!

**Comment by benchen71** [comment]
This request has been added to 1.9.5, which is now available.
