### ISSUE TITLE
My antivirus block EPub Metadata

### ISSUE THREAD

**Issue by gabri25ele** [benchen71/epub-metadata-editor#82]
ESET delete the exe file, virustotal tell me trojan.nanobot/backdoorx
https://www.virustotal.com/gui/file/0aa14c0ac8a9a2462e8ca62caf860c87d5be471b12026982139882aaec7522e7

**Comment by benchen71** [comment]
It's a false positive. There's nothing I can do about it. You might be able to add the file to a white list, if ESET has that functionality.

**Comment by gabri25ele** [comment]
why 1.9.4 doesn't have this problem?

**Comment by benchen71** [comment]
No idea. I make changes in Visual Studio and then compile it to generate the exe. There is definitely no nanobot/backdoor. In fact, since this is open source, you can download the source code, visually inspect it to confirm this, and then compile it yourself. Alternatively, just go back to 1.9.4.
