### ISSUE TITLE
1.9.5 click on Check for update

### ISSUE THREAD

**Issue by w64bit** [benchen71/epub-metadata-editor#83]
Error received when click on Check for update.
![195](https://github.com/benchen71/epub-metadata-editor/assets/29273642/4e9ab917-8469-4a0e-aecb-4baa923f76ef)
[195.txt](https://github.com/benchen71/epub-metadata-editor/files/14001384/195.txt)

**Comment by benchen71** [comment]
Issue confirmed. It seems github may have changed something. I have a fix, so things will work again once 1.9.6 comes along.
