### ISSUE TITLE
Is there a Mac version of this?

### ISSUE THREAD

**Issue by mslmn** [benchen71/epub-metadata-editor#87]
Would like to use it on my Apple Silicon mac.

**Comment by benchen71** [comment]
No. The code is VB.net which, to my knowledge, is not cross-platform.

**Comment by Hae14** [comment]
is there a Possibility for an Android app for this?

**Comment by benchen71** [comment]
No, sorry. The code is very specifically Windows-based.

**Comment by Hae14** [comment]
ohw, that's sad but thanks 4 replying.
..the App I'm using is Outdated & doesn't Work with the Newer Android OS anymore. So I guess I'm gonna install a VM (F1VM) once again so I can Continue Using it XD
