### ISSUE TITLE
Version 1.97: Process cannot access the file cover.jpeg 

### ISSUE THREAD

**Issue by FlameOn66** [benchen71/epub-metadata-editor#88]
When using the Batch Operations - Sequentialise all files into series, it crashes with an error msg:
**The process cannot access the file cover.jpeg because it is being used by another process.**

Here's the debug text:
[Debug.txt](https://github.com/user-attachments/files/17355619/Debug.txt)

Any help would be appreciated - this is a great bit of software!

**Comment by benchen71** [comment]
I have definitely used that function successfully. There might be something specific about the files in question. If there aren't too many in the series, try sequentialising the first two and see if it gives the same error message. If it does, could you attach the files to this chat? (I will delete them once I've downloaded them. You will need to change the file extensions from EPUB to JPG to attach them.) If it works fine, try sequentialising the first three files. Then the first four. When you get the error message, please attach the last file here.
