### ISSUE TITLE
"ERROR: Table of Contents file not found. This ebook is malformed"

### ISSUE THREAD

**Issue by Korb** [benchen71/epub-metadata-editor#89]
When trying to open an epub book in EPUB Metadata Editor that displays correctly in Sumatra PDF and Calibre, an error message appears:

> Table of Contents file not found. This ebook is malformed.

After making changes to the metadata (which was initially displayed after opening), EPUB Metadata Editor displays an error message:

> The EPUB failed to save properly.

If it is impossible to make changes to metadata without a Table of Contents file, then please consider creating an empty Table of Contents file in the epub container using the EPUB Metadata Editor application itself. Alternatively, prompting the user to do so and warning that opening the file without creating a Table of Contents file will not allow changing the metadata, but only reading it.

EPUB Metadata Editor v1.9.7 (EPubMetadataEditorNoInstaller.zip)
Microsoft Windows 10.0.19045.5011

Upd. Alternatively, can you offer the user to convert the book to epub3, which does not require the presence of a toc.ncx file in the container?

**Comment by benchen71** [comment]
Converting from epub2 to epub3 is way beyond my programming abilities. However, there may be something specific (other than a missing TOC) with your EPUB file. Change the extension from EPUB to JPG and attach to this thread. I will delete it after downloading it.

**Comment by Korb** [comment]
@benchen71

![ERROR  Table of Contents file not found  This ebook is malformed epub](https://github.com/user-attachments/assets/ac76db41-6a85-45ef-9e6d-ab5e3c785a23)

**Comment by benchen71** [comment]
File received. When I get a chance I will see if I can do anything about the problem.

**Comment by benchen71** [comment]
I cannot confirm your issue. Using the file you supplied, I can open, make changes, and then save changes after. Yes, the error message about the TOC not being found displays when the program opens. But the program is still able to make changes to the metadata and save those changes afterwards.
