### ISSUE TITLE
Add `Sanitize` button

### ISSUE THREAD

**Issue by Korb** [benchen71/epub-metadata-editor#92]
Clicking on it clears all form fields.

**Comment by benchen71** [comment]
Added to the upcoming version 2.0.0.
One question though: should this button also remove the existing cover image?

**Comment by Korb** [comment]
> should this button also remove the existing cover image?

https://github.com/benchen71/epub-metadata-editor/issues/95#issuecomment-2540904907 — you answered your own question. You are sure that no one needs to remove covers. I think this discussion can be closed. As well as this issue.
