### ISSUE TITLE
Add the `Delete image` item to the cover's context menu

### ISSUE THREAD

**Issue by Korb** [benchen71/epub-metadata-editor#95]
Currently, the context menu only contains the following items:

1. Add image…
2. Change image…
3. Use existing image…
4. Paste image
5. Save image as…

**Comment by benchen71** [comment]
Why would you not want a cover?!? If you really don't want a cover, you will have to delete the relevant lines in the OPF file manually using the "Edit .opf file" button in the Advanced Tasks panel.

**Comment by Korb** [comment]
> Why would you not want a cover?!?

Calibre inserts a generated cover if there is no scanned cover. And most of the time they are terrible. I would rather have no covers at all than have them be so unaesthetic. At least until I find the time to find the correct cover for this edition of the book and add it myself.

> @benchen71 closed this as completed 2 hours ago

Did you mean "not planned"? After all, the "Delete image" option will not appear in the next release.
