### ISSUE TITLE
Make it more obvious what the differences are between the options for selecting a cover image file

### ISSUE THREAD

**Issue by Korb** [benchen71/epub-metadata-editor#96]
Three items from the cover context menu open a dialog box to select a graphic file. I believe that at present it is not clear how the items `Add image...`, `Change image...` and `Use existing image...` differ from each other. As far as I understand, they all allow you to specify an image for the cover of an open EPUB document.

**Comment by benchen71** [comment]
"Add image..." allows you to add an image if there is no image yet defined.
"Change image..." allows you to change the existing cover image to one that is not currently in the EPUB file.
"Use existing image..." allows you to choose as the cover image one that is already in the EPUB file.

I can't really get all that into the menu items text (and menus don't have tool tips) - but now you know what they do!

**Comment by Korb** [comment]
> @benchen71 closed this as completed 2 hours ago

Did you mean "not planned"? After all, for new users the items in the interface have not become more obvious.
