### ISSUE TITLE
Dragging multiple files onto the `Batch Operations` list box does not work

### ISSUE THREAD

**Issue by Korb** [benchen71/epub-metadata-editor#97]
I try to drag multiple EPUB-files from Windows File Explorer search results onto the batch file list window (Under the `Select Files...` and `Clear List` buttons), but instead of adding them to the list, the application behaves as if it opens the files one by one.

EPUB Metadata Editor 1.9.7
Microsoft Windows 10.0.19045.5198

**Comment by benchen71** [comment]
Fixed in the upcoming version 2.0.0.
