### ISSUE TITLE
Add Dark theme

### ISSUE THREAD

**Issue by Korb** [benchen71/epub-metadata-editor#98]
In situations where all other applications are displayed in dark tones, and the work takes place in a darkened room, a bright editor window is very unpleasant for the eyes. Please add the ability to enable a dark color theme for the application. Preferably with the function of detecting the system theme.

**Comment by benchen71** [comment]
As far as I know there is no "quick fix" for implementing dark/light mode in VB 2008. Fortunately, since the project is open source, if you really want a dark mode version of the program, you can fork the project on GitHub and change the colours yourself.

**Comment by Korb** [comment]
> @benchen71 closed this as **completed** 2 hours ago

That is, **not planned**.

**Comment by benchen71** [comment]
Correct. There is no button on GitHub to close an issue as "not planned" though.
